name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore ./src/src.csproj
    - name: Build
      run: dotnet build ./src/src.csproj --no-restore
    - name: Source
      run: dotnet nuget add source https://nuget.pkg.github.com/AdventureWorks-fullstack/index.json --name github --username Stahhl --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text 
    - name: Pack
      run: dotnet pack ./src/src.csproj --configuration Release --version-suffix $GITHUB_RUN_NUMBER
    - name: Push
      run: dotnet nuget push ./src/bin/Release/*.nupkg --api-key ${{ secrets.GITHUB_TOKEN }} --source "github"
